### ISSUE TITLE
Workspace service

### ISSUE THREAD

**Issue by stephanebenayoun** [capsulajs/capsulahub-core#3]
## General description
Workspace is the core service of CapsulaHub, it is responsible for :
- Loading services and components that are included in its configuration
- Allowing them to register themselves
- Letting them communicate together

The service provides a factory to create Workspaces.
The Workspace has to be created with a token that will be used to get its own configuration.

#### Prerequisites
None.

#### Design description
https://github.com/capsulajs/workspace-service/pull/18

- [ ] Is it backward compatible ?
- [x] Adds new API
- [ ] Changes existing API
- [ ] Removes existing API

#### Consideration
- Each extension that will be imported will have in its context access to CAPSULAHUB_WORKSPACE and CAPSULAHUB_CONFIG
- The services that composed the workspace are standalone and should include a bootstrap code that will call `registerService` method

### Test cases
https://github.com/capsulajs/workspace-service/pull/15

## Ready for implementation
- [x] External dependencies have been resolved
- [x] API has been approved
- [x] Test cases have been prepared
- [x] Discussed with Technical lead

## Definition of Done
- [x] Maintainer review
- [x] All tests are implemented
- [ ] Manual QA
- [ ] Documentation
- [ ] Release notes

## RoadMap
Each method of Workspace can be developed/merged separately, preferably in this order :
1. CreateWorkspace (WorkspaceFactory)
2. Register service
3. Services
4. Components
