### ISSUE TITLE
Support multiple configuration providers in Workspace

### ISSUE THREAD

**Issue by dmitriyslaym** [capsulajs/capsulahub-core#32]
## General description
A user should be able to specify which kind of configuration service he wants to use in the current workspace.
1) "localFile": FileProvider
2) "hardcoreServer": "HardcoreRemote"
3) "httpFile": "HttpFile"
4) "httpServer": "HttpProvider"
5) "localStorage": "LocalStorage"

getProvider() util from ConfigurationService should be used to get an appropriate Provider.

#### List of core packages that if affects
workspace

## API

type ConfigurationProvider = 'localFile' | 'hardcoreServer' | 'httpFile' | 'httpServer' | 'localStorage';

interface CreateWorkspaceRequest {
  /** Token used to get workspace configuration */
  token: string;
  /**
   * The type of configuration provider, that will be used to get configuration
   * @default "httpFile"
   */
  configProvider?: ConfigurationProvider;
}

#### Design description

- [ ] Is it backward compatible ?
- [ ] Adds new API
- [x] Changes existing API
- [ ] Removes existing API

#### Changes

Provide link to a PR or code snippet of old and new API.

## Technical considerations
Change the format of configuration file to json and serve it from localhost

## Behavior

- [x] Does the suggested changes impact the current behaviour ?
Workspace config file should be in json file and static server should serve it.
- [ ] Does the suggested changes are specific to some devices/browsers/environments
- [x] Does the suggested changes require to add new dependencies to the package ?
Need to import all types of Configuration Providers

## Test cases

Link to the PR with test cases:
https://github.com/capsulajs/capsulahub-core/pull/34

## Ready for implementation
- [x] External dependencies have been resolved
- [x] API has been approved
- [x] Test cases have been prepared
- [x] Discussed with Technical lead

## Definition of Done
- [x] Maintainer review
- [x] All tests are implemented 
- [x] Documentation
- [x] Release notes

## RoadMap

In case there is more than one mergeable point you can specify it here.

**Comment by stephanebenayoun** [comment]
Need to be updated according to https://github.com/capsulajs/configuration-service/issues/21
